spring.application.name=commerceflow

spring.datasource.url=jdbc:postgresql://localhost:5432/commerceflow_db
spring.datasource.username=postgres
spring.datasource.password= Ashu@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
